name: API Framework

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '18 20 * * *'
  workflow_dispatch:

permissions:
  contents: read        # repo code read करने के लिए
  actions: read         # actions metadata access
  checks: write         # check results update करने के लिए
  issues: write         # (optional) issues create/update
  pull-requests: write  # PR comments/status

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: logs/
